# Generated by Django 5.1.1 on 2024-11-03 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_description',
            new_name='offer_desc',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_item_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_image_url',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fthenounproject.com%2Fbrowse%2Ficons%2Fterm%2Fimage-default%2F&psig=AOvVaw0AmbHrPZZfAhJINI2MKJQP&ust=1730758995426000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPDKxOqZwYkDFQAAAAAdAAAAABAI', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
