# Generated by Django 5.1.1 on 2024-11-20 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=100)),
                ('offer_desc', models.TextField(max_length=500)),
                ('offer_image_url', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fthenounproject.com%2Fbrowse%2Ficons%2Fterm%2Fimage-default%2F&psig=AOvVaw0AmbHrPZZfAhJINI2MKJQP&ust=1730758995426000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPDKxOqZwYkDFQAAAAAdAAAAABAI', max_length=500)),
                ('date_offered', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_directed', models.BooleanField(default=False)),
                ('offer_status', models.CharField(choices=[('CLOSED', 'Closed'), ('PENDING', 'Pending'), ('STANDBY', 'Standby')], default='STANDBY', max_length=20)),
                ('directed_offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.offer')),
                ('offer_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
    ]
