# Generated by Django 5.1.3 on 2024-12-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
