# Generated by Django 5.1.1 on 2024-11-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offer_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Rating',
            new_name='value',
        ),
    ]
