# Generated by Django 5.1.1 on 2024-11-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
