# Generated by Django 5.1.3 on 2024-12-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auction_is_deleted'),
        ('main', '0004_rename_rating_rating_value'),
    ]

    operations = [
    ]
