# Generated by Django 5.1.3 on 2024-12-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20241209_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted_offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aoffer', to='main.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='directed_offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doffer', to='main.offer'),
        ),
    ]
