# Generated by Django 5.1.1 on 2024-11-03 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_first_name_remove_profile_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_title', models.CharField(max_length=100)),
                ('auction_description', models.TextField(max_length=500)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('minimum_bid', models.FloatField(default=0.0)),
                ('highest_bid', models.FloatField(default=0.0)),
                ('auction_status', models.CharField(choices=[('NOT STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='NOT STARTED', max_length=20)),
                ('auction_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('highest_bidder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuctionItem',
        ),
    ]
