# Generated by Django 5.1.1 on 2024-11-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auction_delete_auctionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=4092, null=True),
        ),
    ]
