# Generated by Django 5.1.3 on 2024-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_offer_accepted_offer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default_profile_pic.jpg', upload_to='images/'),
        ),
    ]
