# Generated by Django 5.1.1 on 2024-11-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_image_url_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grang', models.CharField(max_length=10)),
            ],
        ),
    ]
