# Generated by Django 5.1.3 on 2024-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_bio_rating_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('PENDING', 'Pending'), ('STANDBY', 'Standby'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='STANDBY', max_length=20),
        ),
    ]
