# Generated by Django 5.1.1 on 2024-11-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_gogle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gogle',
        ),
    ]
